version: '3.6'
services:
  lab_deploy:
    image: kaioaresi/lab_deploy:qa
    environment:
      - "WSO2_APIMANAGER_URL=${WSO2_APIMANAGER_URL}"
      - "AUTHENTICATION_CONFIG_LOGIN_URL=${AUTHENTICATION_CONFIG_LOGIN_URL}"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      placement:
        constraints:
          - node.role == manager
