version: '3.6'
services:
  lab_deploy:
    image: kaioaresi/lab_deploy:qa
    env_file:
      - .env
    environment:
      - "WSO2_APIMANAGER_URL=${WSO2_APIMANAGER_URL}"
      - "AUTHENTICATION_CONFIG_LOGIN_URL=${AUTHENTICATION_CONFIG_LOGIN_URL}"
      - "TESTE=${TESTE}"
